language: dart
script:
  - cd fimber
dart:
  # Install the latest stable release
  - stable

  #- dartfmt
  # Warnings are fatal, but we only analyze the lib/ directory.
  #- dartanalyzer: --fatal-warnings lib