name: fimber
description: Extensible logging for Flutter - based on Timber on Andoird, using similar (as far as Dart lang allows) method API with same concepts for tree and planting logging tree.
version: 0.4.2
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dev_dependencies:
  test: '^1.5.1'
  pedantic: '^1.7.0'
