name: flutter_fimber
description: Flutter extension for Fimber logging API, it will use native OS Logging statements via channel.
version: 0.4.3
homepage: https://github.com/magillus/flutter-fimber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fimber: 
    path: ../fimber

  flutter:
    sdk: flutter

dev_dependencies:
  test: '^1.15.3'
  pedantic: '^1.8.0'

flutter:
  plugin:
    androidPackage: com.perlak.flutterfimber
    pluginClass: FlutterFimberPlugin
