name: flutter_fimber
description: Flutter extension for Fimber logging API.
version: 0.0.1
author: Mateusz Perlak <mati.akip@gmail.com>
homepage: https://github.com/magillus/flutter-fimber

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  fimber:
    path: ../fimber


  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutterfimber
    pluginClass: FlutterFimberPlugin
