name: flutter_fimber
description: Flutter extension for Fimber logging API, it will use native OS Logging statements via channel.
version: 0.7.0
homepage: https://github.com/magillus/flutter-fimber

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  fimber: ^0.7.0

dev_dependencies:
  test: '^1.0.0'
  flutter_lints: '^2.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.magillus.flutterfimber
        pluginClass: FlutterFimberPlugin
      ios:
        pluginClass: FlutterFimberPlugin
