name: flutter_fimber
description: Flutter extension for Fimber logging API, it will use native OS Logging statements via channel.
version: 0.7.0
homepage: https://github.com/magillus/flutter-fimber

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=2.0.0'

dependencies:
  plugin_platform_interface: ^2.1.4
  flutter:
    sdk: flutter
  fimber: ^0.7.0

dev_dependencies:
  test: '^1.24.1'
  flutter_lints: '^2.0.0'
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.magillus.flutterfimber
        pluginClass: FlutterFimberPlugin
        sharedDarwinSource: true
      ios:
        pluginClass: FlutterFimberPlugin
        sharedDarwinSource: true
