name: fimber_io
description: Fimber version with File logging via dart:io package
version: 0.3.3
author: Mateusz Perlak <mati.akip@gmail.com>
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fimber:
    path: ../fimber

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
