name: fimber_io
description: Fimber version with File logging via dart:io package
version: 0.3.3
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fimber: ^0.3.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
