name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.5.0-nullsafety.1
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: ">=2.12.0-0 <3.0.0"

publish_to: none

dependencies:
  fimber: #^0.5.0-nullsafety.1
    git:
      url: git@github.com:magillus/flutter-fimber
      path: fimber
      ref: nullsafety.update

dev_dependencies:
  test: '^1.16.0-nullsafety'
  pedantic: '^1.10.0-nullsafety'
