name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.4.2
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fimber: ^0.4.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
