name: fimber_io
description: Version of Fimber package with support for File based loggers - dependent on dart::io
version: 0.4.4
homepage: https://github.com/magillus/flutter-fimber/tree/master/fimber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fimber:
    path: ../fimber
  # fimber: ^0.4.4

dev_dependencies:
  test: '^1.15.3'
  pedantic: '^1.8.0'
