name: Analyze Code Style

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze_code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: 2.2.2

      - name: Install dependencies - Fimber
        run: cd fimber && flutter pub get

      - name: Analyze project source - Fimber
        run: cd fimber && flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings

      - name: Install dependencies - Fimber IO
        run: cd fimber_io && flutter pub get

      - name: Analyze project source - Fimber
        run: cd fimber_io && flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings

      - name: Install dependencies - Fimber
        run: cd flutter_fimber && flutter pub get

      - name: Analyze project source - Fimber
        run: cd flutter_fimber && flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings
