# src: https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

name: Flutter Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - name: Install dependencies - Fimber
        run: cd fimber && flutter pub get
      - run: cd fimber && flutter config --enable-web
      - name: Run tests - Fimber
        run: cd fimber && flutter test
      - name: Install dependencies - Fimber IO
        run: cd fimber_io && flutter pub get
      - run: cd fimber_io && flutter config --enable-web
      - name: Run tests - Fimber IO
        run: cd fimber_io && flutter test
      - name: Install dependencies - Flutter Fimber
        run: cd flutter_fimber && flutter pub get
      - run: cd flutter_fimber && flutter config --enable-web
      - name: Run tests - Fimber
        run: cd flutter_fimber && flutter test


