# src: https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

name: Flutter Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: example/

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - name: Install dependencies - Fimber
        run: cd fimber && flutter pub get
      - run: cd fimber && flutter config --enable-web
      - name: Run tests - Fimber
        run: cd fimber && flutter test
      - name: Install dependencies - Fimber IO
        run: cd fimber_io && flutter pub get
      - run: cd fimber_io && flutter config --enable-web
      - name: Run tests - Fimber IO
        run: cd fimber_io && flutter test
      - name: Install dependencies - Flutter Fimber
        run: cd flutter_fimber && flutter pub get
      - run: cd flutter_fimber && flutter config --enable-web
      - name: Run tests - Fimber
        run: cd flutter_fimber && flutter test

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web

  build_ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - run: cd flutter_fimber && flutter pub get
      - run: cd flutter_fimber && flutter clean
      - run: cd flutter_fimber && flutter build ios --release --no-codesign

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - run: cd flutter_fimber && flutter pub get
      - run: cd flutter_fimber && flutter build appbundle

